name: âš™ï¸ Auto-Generator

on: pull_request

jobs:
  docs_site:
    runs-on: ubuntu-latest
    name: ğŸ“„ Docs site files
    steps:
      # first checkout your code
      - name: Checkout ğŸ›
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node_modules ğŸ“¦
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-generator

      - name: Install AsyncAPI Generator ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm i @asyncapi/generator

      # Use AsyncAPI generator to generate the HTML bundle
      - name: Generate docs for Hub SantÃ© interface âš™ï¸
        run: npx ag models/hubsante.asyncapi.yaml @asyncapi/html-template -o docs/specs

      - name: Commit files âœ…
        run: |
          git config --local user.email "Docs-Generator[bot]@users.noreply.github.com"
          git config --local user.name "Docs-Generator[bot]"
          git add docs/specs
          # Commit only if needed | Ref.: https://stackoverflow.com/a/8123841/10115198
          git diff-index --quiet HEAD || git commit -m "âš™ï¸ Auto-gÃ©nÃ©ration de la documentation"

      - name: Push changes â¬†ï¸
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}

  models:
    name: ğŸ“¦ Data models
    runs-on: ubuntu-latest

    # Wait for docs_site commit to be done to avoid push errors / commit Race Condition
    # "Updates were rejected because the remote contains work that you do not have locally"
    # Ref.: https://stackoverflow.com/a/65698892
    needs: docs_site

    steps:
      # first checkout your code
      - name: Checkout ğŸ›
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node_modules ğŸ“¦
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modelina

      - name: Install AsyncAPI Generator ğŸ‘¨ğŸ»â€ğŸ’»
        run: cd models && npm ci

      # Use AsyncAPI generator to generate classes
      - name: Generate models based on Hub SantÃ© interface âš™ï¸
        run: cd models && npm run generate

      - name: Commit files âœ…
        run: |
          git config --local user.email "Docs-Generator[bot]@users.noreply.github.com"
          git config --local user.name "Docs-Generator[bot]"
          git add models/generated
          # Commit only if needed | Ref.: https://stackoverflow.com/a/8123841/10115198
          git diff-index --quiet HEAD || git commit -m "âš™ï¸ Auto-gÃ©nÃ©ration des classes"

      - name: Push changes â¬†ï¸
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
